version: '3.3'
services:
    entity-app:
        image: xmonline/xm-ms-entity:${IMAGE_TAG:-latest}
        networks:
            - xm2
        env_file:
            - ./env/entity-app.env
        volumes:
            - type: bind
              source: /opt/ext-lib/
              target: /opt/ext-lib/
              read_only: true
        secrets:
            - source: SPRING_DATASOURCE_PASSWORD
              target: SPRING_DATASOURCE_PASSWORD
            - source: APPLICATION_AMAZON_AWS_ACCESS_KEY_ID
              target: APPLICATION_AMAZON_AWS_ACCESS_KEY_ID
            - source: APPLICATION_AMAZON_AWS_ACCESS_KEY_SECRET
              target: APPLICATION_AMAZON_AWS_ACCESS_KEY_SECRET
            - source: SPRING_DATASOURCE_URL
              target: SPRING_DATASOURCE_URL
            - source: SPRING_DATASOURCE_USERNAME
              target: SPRING_DATASOURCE_USERNAME
            - source: APPLICATION_AMAZON_AWS_TEMPLATE
              target: APPLICATION_AMAZON_AWS_TEMPLATE
            - source: APPLICATION_AMAZON_AWS_ENDPOINT
              target: APPLICATION_AMAZON_AWS_ENDPOINT
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: entity
                syslog-facility: local7
secrets:
    SPRING_DATASOURCE_PASSWORD:
        external: true
    APPLICATION_AMAZON_AWS_ACCESS_KEY_ID:
        external: true
    APPLICATION_AMAZON_AWS_ACCESS_KEY_SECRET:
        external: true
    SPRING_DATASOURCE_URL:
        external: true
    SPRING_DATASOURCE_USERNAME:
        external: true
    APPLICATION_AMAZON_AWS_TEMPLATE:
        external: true
    APPLICATION_AMAZON_AWS_ENDPOINT:
        external: true
networks:
    xm2:
        driver: overlay